from typing import TypedDict, Dict
from langgraph.graph import StateGraph, END
import os
import json
import logging

# Agents
from ..agents.sports_agent import run_sports_agent
from ..agents.tech_agent import run_tech_agent
from ..agents.finance_agent import run_finance_agent

# Core
from ..core.emailer import send_digest_email

# ------------------------------------------------------
# Logging setup
# ------------------------------------------------------
logger = logging.getLogger(__name__)

# ------------------------------------------------------
# GRAPH STATE
# ------------------------------------------------------
class DigestState(TypedDict):
    sports: Dict
    tech: Dict
    finance: Dict
    digest: Dict

# ------------------------------------------------------
# NODES
# ------------------------------------------------------
def sports_node(state: DigestState) -> Dict:
    return {"sports": run_sports_agent()}

def tech_node(state: DigestState) -> Dict:
    return {"tech": run_tech_agent()}

def finance_node(state: DigestState) -> Dict:
    return {"finance": run_finance_agent()}

def aggregate_node(state: DigestState) -> Dict:
    digest = {
        "sports": state.get("sports", {}),
        "tech": state.get("tech", {}),
        "finance": state.get("finance", {})
    }
    return {"digest": digest}

def email_node(state: DigestState) -> Dict:
    logger.info("Entered email node… preparing to send digest email")

    digest = state.get("digest", {})

    html = """
    <html>
    <body style="font-family: Arial, sans-serif; background-color: #f6f8fa; padding: 20px;">
        <div style="max-width: 700px; margin: auto; background: #ffffff; padding: 20px; border-radius: 8px;">
            <h1 style="color:#222;">📰 Daily News Digest</h1>
            <p style="color:#555;">Your personalized summary for today</p>
            <hr>
    """

    def render_section(title, content):
        if not content:
            return ""
        section_html = f"<h2 style='color:#0b5ed7'>{title}</h2>"

        if content.get("summary"):
            section_html += f"""
            <p style="color:#333; line-height:1.6;">
                <b>Summary:</b><br>{content['summary']}
            </p>
            """

        articles = content.get("articles", [])
        if articles:
            section_html += "<ul>"
            for a in articles:
                section_html += f"""
                <li style="margin-bottom:8px;">
                    <a href="{a.get('url', '#')}" style="color:#0d6efd; text-decoration:none;">
                        {a.get('title', 'No title')}
                    </a>
                </li>
                """
            section_html += "</ul>"

        section_html += "<hr>"
        return section_html

    html += render_section("💰 Finance", digest.get("finance"))
    html += render_section("💻 Technology", digest.get("tech"))
    html += render_section("🏏 Sports", digest.get("sports"))

    html += """
            <p style="font-size:12px; color:#888;">
                Generated by Agentic AI News Summarizer
            </p>
        </div>
    </body>
    </html>
    """

    send_digest_email(
        subject="📰 Daily News Digest",
        html_body=html
    )

    logger.info("Digest email sent successfully")
    return {"status": "sent"}



# ------------------------------------------------------
# GRAPH BUILD
# ------------------------------------------------------
def build_news_digest_graph():
    graph = StateGraph(DigestState)

    # Add nodes
    graph.add_node("sports", sports_node)
    graph.add_node("tech", tech_node)
    graph.add_node("finance", finance_node)
    graph.add_node("aggregate", aggregate_node)
    graph.add_node("email", email_node)

    # Parallel fan-out
    graph.set_entry_point("sports")
    graph.add_edge("sports", "tech")
    graph.add_edge("tech", "finance")

    # Fan-in
    graph.add_edge("finance", "aggregate")
    graph.add_edge("aggregate", "email")
    graph.add_edge("email", END)

    return graph.compile()

# ------------------------------------------------------
# EXECUTION ENTRY
# ------------------------------------------------------
def run_news_digest():
    graph = build_news_digest_graph()
    graph.invoke({})
